export enum ActionType {
    UPDATE_SHIFTS_UI_SHIFTS,
    UPDATE_SHIFTS_UI_SHIFT_TYPES,
    ADD_SHIFTS_UI_SHIFT_PARTICIPATION,
    UPDATE_SHIFTS_UI_SHIFT_PARTICIPATIONS,
    UPDATE_SHIFTS_UI_SHIFT_PARTICIPATION,
    UPDATE_SHIFTS_UI_SHIFT,
    CREATE_SHIFTS_UI_SHIFT,
    DELETE_SHIFTS_UI_SHIFT,
    DELETE_SHIFTS_UI_SHIFT_PARTICIPATION,
    UPDATE_SHIFTS_UI_EMPLOYEES,
    UPDATE_SHIFTS_UI_SHIFT_COMMENTS,
    UPDATE_SHIFTS_UI_SHIFT_PARTICIPATION_TYPES,
    UPDATE_SHIFTS_UI_SHIFT_GROUPS
}