export enum ActionType {
    GET_SHIFTS_BETWEEN_DATES,
    GET_SHIFT_TYPES,
    CREATE_SHIFT_PARTICIPATION,
    CREATE_SHIFT_PARTICIPATIONS_FROM_GROUP,
    GET_SHIFT_PARTICIPATIONS,
    UPDATE_SHIFT_PARTICIPATION,
    CREATE_SHIFT,
    DELETE_SHIFT,
    DELETE_SHIFT_PARTICIPATION,
    MOVE_SHIFT_PARTICIPATION,
    GET_EMPLOYEES,
    UPDATE_SHIFT_COMMENTS,
    GET_SHIFT_GROUPS
}