// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OSS.App.Data;

#nullable disable

namespace OSS.Web.Migrations;

[DbContext(typeof(AppIdentityDbContext))]
[Migration("20250530115831_DotnetTime")]
partial class DotnetTime
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex");

                b.ToTable("AspNetRoles", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("text");

                b.Property<string>("ClaimValue")
                    .HasColumnType("text");

                b.Property<string>("RoleId")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("AspNetRoleClaims", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("text");

                b.Property<string>("ClaimValue")
                    .HasColumnType("text");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserClaims", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasColumnType("text");

                b.Property<string>("ProviderKey")
                    .HasColumnType("text");

                b.Property<string>("ProviderDisplayName")
                    .HasColumnType("text");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("LoginProvider", "ProviderKey");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserLogins", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("text");

                b.Property<string>("RoleId")
                    .HasColumnType("text");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("AspNetUserRoles", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("text");

                b.Property<string>("LoginProvider")
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .HasColumnType("text");

                b.Property<string>("Value")
                    .HasColumnType("text");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("AspNetUserTokens", (string)null);
            });

        modelBuilder.Entity("OSS.Domain.Entities.ApplicationUser", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("integer");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("text");

                b.Property<string>("Designation")
                    .HasColumnType("text");

                b.Property<string>("DisplayName")
                    .HasColumnType("text");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("boolean");

                b.Property<int>("GenderId")
                    .HasColumnType("integer");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("boolean");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("OfficeId")
                    .HasColumnType("text");

                b.Property<string>("PasswordHash")
                    .HasColumnType("text");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("text");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("boolean");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("text");

                b.Property<int>("ShiftGroupId")
                    .HasColumnType("integer");

                b.Property<int?>("ShiftRoleId")
                    .HasColumnType("integer");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("boolean");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.HasKey("Id");

                b.HasIndex("GenderId");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex");

                b.HasIndex("ShiftGroupId");

                b.HasIndex("ShiftRoleId");

                b.ToTable("AspNetUsers", (string)null);
            });

        modelBuilder.Entity("OSS.Domain.Entities.EmployeeShiftSkill", b =>
            {
                b.Property<string>("EmployeeId")
                    .HasColumnType("text");

                b.Property<int>("ShiftSkillId")
                    .HasColumnType("integer");

                b.Property<int>("Id")
                    .HasColumnType("integer");

                b.HasKey("EmployeeId", "ShiftSkillId");

                b.HasIndex("ShiftSkillId");

                b.ToTable("EmployeeShiftSkills");
            });

        modelBuilder.Entity("OSS.Domain.Entities.Gender", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("Genders");
            });

        modelBuilder.Entity("OSS.Domain.Entities.LeaveRequest", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("Created")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("CreatedById")
                    .HasColumnType("text");

                b.Property<string>("EmployeeId")
                    .HasColumnType("text");

                b.Property<DateTime>("EndDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("ExecutedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsApproved")
                    .HasColumnType("boolean");

                b.Property<bool>("IsExecuted")
                    .HasColumnType("boolean");

                b.Property<DateTime?>("LastModified")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("LastModifiedById")
                    .HasColumnType("text");

                b.Property<int>("LeaveTypeId")
                    .HasColumnType("integer");

                b.Property<string>("Remarks")
                    .HasColumnType("text");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("CreatedById");

                b.HasIndex("LastModifiedById");

                b.HasIndex("LeaveTypeId");

                b.HasIndex("EmployeeId", "StartDate", "EndDate")
                    .IsUnique();

                b.ToTable("LeaveRequests");
            });

        modelBuilder.Entity("OSS.Domain.Entities.LeaveRequestComment", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Comment")
                    .HasColumnType("text");

                b.Property<DateTime>("Created")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("CreatedById")
                    .HasColumnType("text");

                b.Property<DateTime?>("LastModified")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("LastModifiedById")
                    .HasColumnType("text");

                b.Property<int>("LeaveRequestId")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("CreatedById");

                b.HasIndex("LastModifiedById");

                b.HasIndex("LeaveRequestId");

                b.ToTable("LeaveRequestComments");
            });

        modelBuilder.Entity("OSS.Domain.Entities.Shift", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Comments")
                    .HasColumnType("text");

                b.Property<DateTime>("ShiftDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("ShiftTypeId")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("ShiftTypeId", "ShiftDate")
                    .IsUnique();

                b.ToTable("Shifts");
            });

        modelBuilder.Entity("OSS.Domain.Entities.ShiftCycleItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("ShiftSequence")
                    .HasColumnType("integer");

                b.Property<int>("ShiftTypeId")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("ShiftSequence")
                    .IsUnique();

                b.HasIndex("ShiftTypeId");

                b.ToTable("ShiftCycleItems");
            });

        modelBuilder.Entity("OSS.Domain.Entities.ShiftGroup", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("ShiftGroups");
            });

        modelBuilder.Entity("OSS.Domain.Entities.ShiftParticipation", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("EmployeeId")
                    .HasColumnType("text");

                b.Property<int>("ParticipationSequence")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasDefaultValue(0);

                b.Property<int>("ShiftId")
                    .HasColumnType("integer");

                b.Property<int>("ShiftParticipationTypeId")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("EmployeeId");

                b.HasIndex("ShiftParticipationTypeId");

                b.HasIndex("ShiftId", "EmployeeId")
                    .IsUnique();

                b.ToTable("ShiftParticipations");
            });

        modelBuilder.Entity("OSS.Domain.Entities.ShiftParticipationType", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("BgClrString")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("text")
                    .HasDefaultValue("#000000");

                b.Property<string>("ColorString")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("text")
                    .HasDefaultValue("#FFFFFF");

                b.Property<bool>("IsAbsence")
                    .HasColumnType("boolean");

                b.Property<bool>("IsBold")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("boolean")
                    .HasDefaultValue(false);

                b.Property<string>("Name")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("ShiftParticipationTypes");
            });

        modelBuilder.Entity("OSS.Domain.Entities.ShiftRole", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("RoleName")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("RoleName")
                    .IsUnique();

                b.ToTable("ShiftRoles");
            });

        modelBuilder.Entity("OSS.Domain.Entities.ShiftSkill", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("ShiftSkills");
            });

        modelBuilder.Entity("OSS.Domain.Entities.ShiftType", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("ColorString")
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .HasColumnType("text");

                b.Property<int>("ShiftSequence")
                    .HasColumnType("integer");

                b.Property<int>("StartOffsetHrs")
                    .HasColumnType("integer");

                b.Property<int>("StartOffsetMins")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("ShiftTypes");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.HasOne("OSS.Domain.Entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.HasOne("OSS.Domain.Entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("OSS.Domain.Entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.HasOne("OSS.Domain.Entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("OSS.Domain.Entities.ApplicationUser", b =>
            {
                b.HasOne("OSS.Domain.Entities.Gender", "Gender")
                    .WithMany()
                    .HasForeignKey("GenderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("OSS.Domain.Entities.ShiftGroup", "ShiftGroup")
                    .WithMany("Employees")
                    .HasForeignKey("ShiftGroupId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("OSS.Domain.Entities.ShiftRole", "ShiftRole")
                    .WithMany()
                    .HasForeignKey("ShiftRoleId");

                b.Navigation("Gender");

                b.Navigation("ShiftGroup");

                b.Navigation("ShiftRole");
            });

        modelBuilder.Entity("OSS.Domain.Entities.EmployeeShiftSkill", b =>
            {
                b.HasOne("OSS.Domain.Entities.ApplicationUser", "Employee")
                    .WithMany("EmployeeShiftSkills")
                    .HasForeignKey("EmployeeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("OSS.Domain.Entities.ShiftSkill", "ShiftSkill")
                    .WithMany()
                    .HasForeignKey("ShiftSkillId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Employee");

                b.Navigation("ShiftSkill");
            });

        modelBuilder.Entity("OSS.Domain.Entities.LeaveRequest", b =>
            {
                b.HasOne("OSS.Domain.Entities.ApplicationUser", "CreatedBy")
                    .WithMany()
                    .HasForeignKey("CreatedById");

                b.HasOne("OSS.Domain.Entities.ApplicationUser", "Employee")
                    .WithMany()
                    .HasForeignKey("EmployeeId");

                b.HasOne("OSS.Domain.Entities.ApplicationUser", "LastModifiedBy")
                    .WithMany()
                    .HasForeignKey("LastModifiedById");

                b.HasOne("OSS.Domain.Entities.ShiftParticipationType", "LeaveType")
                    .WithMany()
                    .HasForeignKey("LeaveTypeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("CreatedBy");

                b.Navigation("Employee");

                b.Navigation("LastModifiedBy");

                b.Navigation("LeaveType");
            });

        modelBuilder.Entity("OSS.Domain.Entities.LeaveRequestComment", b =>
            {
                b.HasOne("OSS.Domain.Entities.ApplicationUser", "CreatedBy")
                    .WithMany()
                    .HasForeignKey("CreatedById");

                b.HasOne("OSS.Domain.Entities.ApplicationUser", "LastModifiedBy")
                    .WithMany()
                    .HasForeignKey("LastModifiedById");

                b.HasOne("OSS.Domain.Entities.LeaveRequest", "LeaveRequest")
                    .WithMany("LeaveRequestComments")
                    .HasForeignKey("LeaveRequestId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("CreatedBy");

                b.Navigation("LastModifiedBy");

                b.Navigation("LeaveRequest");
            });

        modelBuilder.Entity("OSS.Domain.Entities.Shift", b =>
            {
                b.HasOne("OSS.Domain.Entities.ShiftType", "ShiftType")
                    .WithMany()
                    .HasForeignKey("ShiftTypeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ShiftType");
            });

        modelBuilder.Entity("OSS.Domain.Entities.ShiftCycleItem", b =>
            {
                b.HasOne("OSS.Domain.Entities.ShiftType", "ShiftType")
                    .WithMany()
                    .HasForeignKey("ShiftTypeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ShiftType");
            });

        modelBuilder.Entity("OSS.Domain.Entities.ShiftParticipation", b =>
            {
                b.HasOne("OSS.Domain.Entities.ApplicationUser", "Employee")
                    .WithMany("ShiftParticipations")
                    .HasForeignKey("EmployeeId");

                b.HasOne("OSS.Domain.Entities.Shift", "Shift")
                    .WithMany("ShiftParticipations")
                    .HasForeignKey("ShiftId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("OSS.Domain.Entities.ShiftParticipationType", "ShiftParticipationType")
                    .WithMany()
                    .HasForeignKey("ShiftParticipationTypeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Employee");

                b.Navigation("Shift");

                b.Navigation("ShiftParticipationType");
            });

        modelBuilder.Entity("OSS.Domain.Entities.ApplicationUser", b =>
            {
                b.Navigation("EmployeeShiftSkills");

                b.Navigation("ShiftParticipations");
            });

        modelBuilder.Entity("OSS.Domain.Entities.LeaveRequest", b =>
            {
                b.Navigation("LeaveRequestComments");
            });

        modelBuilder.Entity("OSS.Domain.Entities.Shift", b =>
            {
                b.Navigation("ShiftParticipations");
            });

        modelBuilder.Entity("OSS.Domain.Entities.ShiftGroup", b =>
            {
                b.Navigation("Employees");
            });
#pragma warning restore 612, 618
    }
}
